### ISSUE TITLE
What is DNS server?

### ISSUE THREAD

**Issue by KhalilFaizi** [Diamond-Family/DNS-Installition-and-Configution#3]
Please add your small sentence about DNS server :

**Comment by Farhadzahin123** [comment]
DNS
DNS (Domain name system) Is a network protocol used to translate hostname into IP address 
DNS is not required establish a network connection.
DNS has to step 
 Forward lookup zone: uses the domain name to search for IP address 
Server.exmple.com
192.168.23.1
 Revers lookup zone: use IP address to search for the domain name

**Comment by Abdulmateenmaher** [comment]
a server which seems as(lookup) systems 
translates name to ip and it vice versa
