### ISSUE TITLE
Conclusion of DNS

### ISSUE THREAD

**Issue by KhalilFaizi** [Diamond-Family/DNS-Installition-and-Configution#9]
Please add your information
Here:

**Comment by mokhtar003** [comment]
Original contributions presented in this section are novel methodologies for modeling DNS traffic by means of graphs. During the validation on the “.it” ccTLD authoritative name servers, we found that DNS resolvers degrees are highly-skewed and obey power laws. This fact also holds for Internet domains when considering all traffic or just a portion of it such as web or email. These findings give new insight into the scale-free nature of the DNS system, where a few resolvers and a few domains are responsible for most of the DNS activity.
